appname: "eru"
entrypoints:
  agent:
    cmd: "/usr/bin/eru-agent --config /agent.yaml"
    restart: always
    publish:
      - "12345"
    healthcheck:
      tcp_ports:
        - "12345"
    privileged: true
    log:
      type: "none"
volumes:
  - /sys:/sys:ro
  - /var/run/docker.sock:/var/run/docker.sock
  - /proc/:/hostProc/
stages:
  - build
  - pack
builds:
  build:
    base: "golang:alpine"
    # only support ssh protocol
    repo: "git@github.com:projecteru2/agent.git"
    version: "HEAD"
    dir: /go/src/github.com/projecteru2/agent
    commands:
      - apk add --no-cache git curl make gcc libc-dev
      - make test
      - make binary
      - ./eru-agent --version
    cache:
      /go/src/github.com/projecteru2/agent/eru-agent: /usr/bin/eru-agent
  pack:
    base: alpine
    labels:
      ERU: 1
      version: latest
      agent: 1
    envs:
      AGENT_IN_DOCKER: 1
    commands:
      - mkdir -p /etc/eru/
